FROM alpine:3.20 AS base

RUN apk add --no-cache wget

# models
RUN mkdir -p /weights/CodeFormer /weights/facelib /weights/realesrgan \
    && wget -q -O /weights/CodeFormer/codeformer.pth \
         https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/codeformer.pth \
    && wget -q -O /weights/facelib/detection_Resnet50_Final.pth \
         https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/detection_Resnet50_Final.pth \
    && wget -q -O /weights/facelib/parsing_parsenet.pth \
         https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/parsing_parsenet.pth \
    && wget -q -O /weights/realesrgan/RealESRGAN_x2plus.pth \
         https://github.com/sczhou/CodeFormer/releases/download/v0.1.0/RealESRGAN_x2plus.pth

# example images
RUN mkdir -p /examples \
    && wget -q -O /examples/01.png "https://replicate.com/api/models/sczhou/codeformer/files/fa3fe3d1-76b0-4ca8-ac0d-0a925cb0ff54/06.png" \
    && wget -q -O /examples/02.jpg "https://replicate.com/api/models/sczhou/codeformer/files/a1daba8e-af14-4b00-86a4-69cec9619b53/04.jpg" \
    && wget -q -O /examples/03.jpg "https://replicate.com/api/models/sczhou/codeformer/files/542d64f9-1712-4de7-85f7-3863009a7c3d/03.jpg" \
    && wget -q -O /examples/04.jpg "https://replicate.com/api/models/sczhou/codeformer/files/a11098b0-a18a-4c02-a19a-9a7045d68426/010.jpg" \
    && wget -q -O /examples/05.jpg "https://replicate.com/api/models/sczhou/codeformer/files/7cf19c2c-e0cf-4712-9af8-cf5bdbb8d0ee/012.jpg"